"""
BUILD file for the base Helm chart.
"""

load("@rules_helm//helm:helm.bzl", "helm_chart", "helm_push")

helm_chart(
    name = "app_chart",
    chart = "Chart.yaml",
    srcs = glob(["templates/*.yaml"]),
    values = "values.yaml",
    visibility = ["//visibility:public"],
)

helm_push(
    name = "push-oci",
    chart = ":app_chart",
    registry = "harbor.example.com",
    repository = "my-project/charts/app",
    tag = "latest",
)
