load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "http_proto",
    srcs = ["http.proto"],
    visibility = ["//visibility:public"],
    deps = ["//google/protobuf:descriptor_proto"],
)

proto_library(
    name = "annotations_proto",
    srcs = ["annotations.proto"],
    deps = [":http_proto", "//google/protobuf:descriptor_proto"],
    visibility = ["//visibility:public"],
)
