"""BUILD file for the Product API v1."""
load("@rules_go//go:def.bzl", "go_library")
load("//tools/bazel:proto.bzl", "go_api_library")

go_api_library(
    name = "product_v1",
    srcs = ["product.proto"],
)

go_library(
    name = "product",
    embed = [":product_v1_go_grpc"],
    importpath = "go-monorepo-template/proto/acme/product/v1",
    visibility = ["//visibility:public"],
)
