syntax = "proto3";

package acme.product.v1;


option go_package = "go-monorepo-template/proto/acme/product/v1";

// The product service definition.
service ProductService {
  // Retrieves a product by its ID.
  rpc GetProduct(GetProductRequest) returns (Product) {}
}

// A product resource.
message Product {
  string product_id = 1;
  string name = 2;
  string description = 3;
  double price = 4;
}

// Request message for GetProduct RPC.
message GetProductRequest {
  // The ID of the product to retrieve.
  string product_id = 1;
}
